### ISSUE TITLE
A small mistake found in your paper

### ISSUE THREAD

**Issue by YunjiePeng** [tteepe/GaitGraph#10]
The results of PoseGait in Table 2 and Table 3 are referenced incorrectly. These results are under the setting of MT(medium-sample training), i.e., 62 for training and the rest for testing. You should use the results of Table 9 in PoseGait for a fair comparison.
By the way, would you like to tell me about the status of your paper? Has it been accepted? I want to cite your good work and only found the arXiv version.

**Comment by tteepe** [comment]
Thanks for the hint, you are right! I'll update the paper. 

The paper was accepted at [ICIP'21](https://2021.ieeeicip.org/Papers/AcceptedPapers.asp) which is in September. For now there is only the arXiv version.
Thanks for the interest in my work, I'm excited to see what you build upon it!
