### ISSUE TITLE
Does 2_evaluate.sh work properly?

### ISSUE THREAD

**Issue by ttk0726** [tteepe/GaitGraph#12]
Hi, thanks for your work.

I executed Gaitgraph / experiments / 2_evaluate.sh, then it gave the following output.
Is this working properly?

`../data/casia-b_pose_valid.csv: 148464: ./074-nm-06-180/000105.jpg,163.31964,59.367306000000006,0.62753356,160.98886000000002,57.036533,0.6496187,163.31964,57.61923,0.6171515999999999,160.40617,57.61923,0.91751564,167.98117,57.61923,0.9350721,156.91002,68.690384,0.90779334,172.64272,68.690384,0.9123460999999999,153.41386,82.09231,0.87953293,174.97348,80.926926,0.877726,153.41386,93.16346999999999,0.86672676,174.97348,90.832695,0.9115324,158.6581,91.998085,0.8330506999999999,169.14656000000002,91.998085,0.8313613999999999,160.40617,110.64424,0.87980276,168.56387,110.0: not found4657,160.40617,129.2904,0.85843027,168.56387,125.79423999999999,0.86784875`

**Comment by tteepe** [comment]
Hi,

ich checked again and `2_evaluate.sh` runs fine for me.
Could you send me the content of your file? It's probably just formatting issue. 

Cheers,
Torben
