### ISSUE TITLE
Can't reproduce the accuracy in the paper

### ISSUE THREAD

**Issue by PEACEandSAFE** [tteepe/GaitGraph#13]
Hi @tteepe 
I run 1_train_casia-b.sh and called ckpt_epoch_best.pth. But the accuracy is a bit low.
![image](https://user-images.githubusercontent.com/30662227/126041705-0e8f840e-2ae6-4bf8-ad13-5a767ffb5adf.png)
I wonder how to reproduce the results in the article. Do I need to set the random seed or reduce lr?
Here is the accuracy graph from tensorboard.
![QQ截图20210717233706](https://user-images.githubusercontent.com/30662227/126042210-af78022d-d8cb-4c94-a4cf-1158c816fc8d.png)

**Comment by YunjiePeng** [comment]
As written in the paper,  the GaitGraph are trained in two cycles. After running the 1_train_casia-b_fine.sh, you should run 1_train_casia-b_fine.sh. In this way, you can reproduce the results in GaitGraph. Hope this can be helpful~

**Comment by YunjiePeng** [comment]
As written in the paper,  the GaitGraph is trained in two cycles. After running the 1_train_casia-b_fine.sh, you should run 1_train_casia-b_fine.sh. In this way, you can reproduce the results in GaitGraph. Hope this can be helpful~

**Comment by PEACEandSAFE** [comment]
> As written in the paper, the GaitGraph is trained in two cycles. After running the 1_train_casia-b_fine.sh, you should run 1_train_casia-b_fine.sh. In this way, you can reproduce the results in GaitGraph. Hope this can be helpful~

It has been solved. Thank you!
