### ISSUE TITLE
Are you willing to share with us the performance of the GaitGraph on other gait datasets?

### ISSUE THREAD

**Issue by YunjiePeng** [tteepe/GaitGraph#14]
Only the performance of the CASIA-B gait dataset is put up on the arxiv version of your paper. In the ./src/common.py, the choices for '--dataset' are ["casia-b", "outdoor-gait", "tum-gaid"]. Would you like to share with us the performance of the GaitGraph on both the "outdoor-gait" and the "tum-gaid"?
In consideration of the relative small number of subjects in "outdoor-gait" and "tum-gaid", have you ever think about the OUMVLP-Pose gait datasets? Both the AlphaPose and the Openpose results are provided in OUMVLP-Pose.
Thanks for the great code sharing and looking forward to your reply.

**Comment by tteepe** [comment]
Yes, the results on OUMVLP-Pose are in the making and I will publish an update to the paper and the source code in coming weeks.

**Comment by YunjiePeng** [comment]
You are so nice! Thanks a million for your kindly help. : )
