### ISSUE TITLE
#Question of input

### ISSUE THREAD

**Issue by logic03** [tteepe/GaitGraph#20]
Why don't you use 3d pose for input? Is it less accurate to use 3d pose?

**Comment by tteepe** [comment]
Don't know mate. Try it out.

**Comment by logic03** [comment]
#Question of 2D coordinates&nbsp;




May I ask whether the 2d data of an input picture refers to the coordinates in the original picture (Picture 1) or the coordinates of the Bbox (Picture 2) obtained by target detection from the original picture?——————————————————————————————————

请问输入的一张图片的二维数据，是指原始图片（图片1）中的坐标，还是从原始图片中进行目标检测得到的bbox（图片2）的坐标呢？


（1）Picture 1



（2）Picture 2










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tteepe/GaitGraph"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tteepe/GaitGraph] #Question of input (Issue #20)





 
Don't know mate. Try it out.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
