### ISSUE TITLE
Question of 2D coordinates

### ISSUE THREAD

**Issue by logic03** [tteepe/GaitGraph#21]
May I ask whether the 2d data of an input picture refers to the coordinates in the original picture (Picture 1) or the coordinates of the Bbox (Picture 2) obtained by target detection from the original picture?
___________________________________________________________________________________
请问输入的一张图片的二维数据，是指原始图片（图片1）中的坐标，还是从原始图片中进行目标检测得到的bbox（图片2）的坐标呢？

**Comment by tteepe** [comment]
It's absolute coordinates in the picture.
