### ISSUE TITLE
Model doesnt resume training 

### ISSUE THREAD

**Issue by syasir1** [tteepe/GaitGraph#26]
Hey,

I am trying to train the model as per your paper i.e., 300 epochs with 1e-2 lr, and then for 100 epochs with lr 1e-5. but the model dos not resume training even when the checkpoint_path argument is passed. it just runs for one epoch and shows 0.00 accuracy, and ends training. Any suggestion as to how I can resolve said issue?

Regards,

Yasir

**Comment by tteepe** [comment]
That's how it was intended. The second cycle trains as it's own training.
