### ISSUE TITLE
Angle code is probably wrong

### ISSUE THREAD

**Issue by HiAleeYang** [tteepe/GaitGraph#27]
https://github.com/tteepe/GaitGraph/blob/030163b8392cd0c748bdacf084831a8590de041e/src/datasets/augmentation.py#L43
you use a loop, but the `data_new[2, C, :, :]` just gets the last value after the loop.
According to the distribution of the Multiple Input Branches in the paper('ResGCN'), it's allowed to calculate i th angle of bone by i th bone length

**Comment by tteepe** [comment]
Yes good find! It is not used in this repo for the reported results. It was corrected in [GaitGraph2](https://github.com/tteepe/GaitGraph2/blob/0c619f370574baf9b0fa62af583588375c896e7c/GaitGraph/transforms/multi_input.py#L33).
