### ISSUE TITLE
Requirements Error

### ISSUE THREAD

**Issue by MritulaC** [tteepe/GaitGraph#5]
Hi, Thanks for the wonderful implementation. I am getting the following error while trying to reproduce Gaitgraph. When I run requirements "!pip3 install -r requirements.txt": I am getting the below error:

ERROR: torchtext 0.9.1 has requirement torch==1.8.1, but you'll have torch 1.7.1 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.

Kindly let me know if this will affect the end result and if yes how to overcome ?

Thanks
Mritula

**Comment by tteepe** [comment]
Hi Mritula,

looks like you are trying to install the requirements in a non clean environment.
Neither `torchtext` nor `albumentations` are part of this project. 

Create a new virtuell environment for this project, see the python documentation:
https://docs.python.org/3/tutorial/venv.html

Cheers,
Torben
