### ISSUE TITLE
Questions about the data.

### ISSUE THREAD

**Issue by zhangzhi-git** [tteepe/GaitGraph#6]
Hello author, thank you for your work. I would like to know how all the video frames recorded in the casia-b_all_frames.csv file are obtained? Because I observed that it may not only save each frame from the video. For example, the video file 015-cl-02-108.avi has 135 frames, but only 65 frames are recorded in your csv file.

**Comment by zhangzhi-git** [comment]
Hello author, thank you for your work. I would like to know how all the video frames recorded in the casia-b_all_frames.csv file are obtained? Because I observed that it may not only save each frame from the video. For example, the video file 015-cl-02-108.avi has 135 frames, but only 65 frames are recorded in your csv file.

**Comment by tteepe** [comment]
Hi,
you are right, my extraction was missing quite some frames...
I rerun the extraction, added the extraction script and updated the instructions (737b03e).

I am also rerunning the preprocessing and experiments. I will upload the new files and close the issue once it is done.

Cheers,
Torben

**Comment by tteepe** [comment]
Hi,

the missing frames were just empty frames that were pre filtered. But the detection stage will sort those frames out anyway.
I rerun everything and got the nearly same results with the full extraction.

Hope that clears it up.

Torben

**Comment by ZziTaiLeo** [comment]
Thank you for your outstanding contributions in this field! I also have some doubts about data processing: although objects exist in the box frame with yolo3, will the entry and exit of objects in the beginning and end of a video lead to frames of mutilated bodies, which have an impact on skeleton estimation, such as skeleton collapse and large changes in nodes?
