### ISSUE TITLE
Unable to execute evaluate.py script

### ISSUE THREAD

**Issue by srikamalteja** [tteepe/GaitGraph#8]
Hi, thanks for your work on this project. I'm a newbie to the deep learning environment and currently my research is on Gait Recognition using GCN.

So, the problem I was facing is, after the successful execution of the train.py, what parameters need to be passed to execute the evaluate.py script?

`!python3 evaluate.py casia-b -- /content/GaitGraph/data/casia-b_pose_coco.csv \
                       -- weights_path /content/GaitGraph/models/gaitgraph_resgcn-n39-r8_coco_seq_60.pth \
                        -- data_path /content/GaitGraph/data/casia-b_pose_valid.csv \
`

I'm getting this error,

`usage: evaluate.py [-h] [--network_name NETWORK_NAME]
                   [--sequence_length SEQUENCE_LENGTH]
                   [--batch_size BATCH_SIZE]
                   [--embedding_layer_size EMBEDDING_LAYER_SIZE]
                   [--use_multi_branch] [--shuffle]
                   {casia-b} weights_path data_path
evaluate.py: error: unrecognized arguments: weights_path /content/GaitGraph/models -- data_path 
`

Can you please help me on this issue?

Thank you.

**Comment by tteepe** [comment]
Hi,

looks like your input parameters are not correctly formatted. 

Check these example parameters here:
https://github.com/tteepe/GaitGraph/blob/737b03e2eddecff15580e2d9a3196a8509184386/experiments/2_evaluate.sh#L3-L6

Cheers,
Torben
